/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Goal {
    id: string;
    endDate?: Time;
    isCompleted: boolean;
    progressPercentage: number;
    name: string;
    targetAmount: number;
    currentAmount: number;
    startDate: Time;
}
export type Time = bigint;
export interface PaymentMethodTotal {
    paymentMethod: PaymentMethod;
    amount: number;
}
export interface UserSettings {
    theme: Variant_dark_light;
    showNotifications: boolean;
    showAnalytics: boolean;
    enableAIInsights: boolean;
    showBudgetWarnings: boolean;
    showSavingsTips: boolean;
}
export interface FinancialInsight {
    savingsPotential: number;
    totalIncome: number;
    incomeExpenseRatio: number;
    totalExpenses: number;
    topSpendingCategory?: Category;
    spendingTrends: Array<number>;
}
export interface CategoryTotal {
    category: Category;
    amount: number;
}
export interface UserProfile {
    name: string;
    email: string;
    memberSince: Time;
}
export interface Transaction {
    id: string;
    paymentMethod: PaymentMethod;
    transactionType: TransactionType;
    date: Time;
    notes: string;
    category: Category;
    amount: number;
}
export enum Category {
    salary = "salary",
    other = "other",
    entertainment = "entertainment",
    food = "food",
    travel = "travel",
    rent = "rent",
    utilities = "utilities",
    investment = "investment",
    freelance = "freelance",
    shopping = "shopping",
    health = "health"
}
export enum PaymentMethod {
    upi = "upi",
    creditCard = "creditCard",
    other = "other",
    cash = "cash",
    bankTransfer = "bankTransfer",
    debitCard = "debitCard"
}
export enum TransactionType {
    expense = "expense",
    income = "income"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_dark_light {
    dark = "dark",
    light = "light"
}
export interface backendInterface {
    addGoal(name: string, targetAmount: number, startDate: Time, endDate: Time | null): Promise<string>;
    addTransaction(amount: number, date: Time, category: Category, paymentMethod: PaymentMethod, notes: string, transactionType: TransactionType): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeGoal(id: string): Promise<void>;
    deleteGoal(id: string): Promise<void>;
    deleteTransaction(id: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategoryTotals(): Promise<Array<CategoryTotal>>;
    getFinancialInsight(): Promise<FinancialInsight | null>;
    getGoals(): Promise<Array<Goal>>;
    getImmutableCategoryTypes(): Promise<Array<Category>>;
    getImmutablePaymentMethods(): Promise<Array<PaymentMethod>>;
    getPaymentMethodTotals(): Promise<Array<PaymentMethodTotal>>;
    getTransactions(): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSettings(): Promise<UserSettings | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveFinancialInsight(insight: FinancialInsight): Promise<void>;
    saveUserSettings(settings: UserSettings): Promise<void>;
    updateGoal(id: string, name: string, targetAmount: number, currentAmount: number, endDate: Time | null): Promise<void>;
    updateTransaction(id: string, amount: number, date: Time, category: Category, paymentMethod: PaymentMethod, notes: string, transactionType: TransactionType): Promise<void>;
}
import type { Category as _Category, CategoryTotal as _CategoryTotal, FinancialInsight as _FinancialInsight, Goal as _Goal, PaymentMethod as _PaymentMethod, PaymentMethodTotal as _PaymentMethodTotal, Time as _Time, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole, UserSettings as _UserSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGoal(arg0: string, arg1: number, arg2: Time, arg3: Time | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addGoal(arg0, arg1, arg2, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGoal(arg0, arg1, arg2, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg3));
            return result;
        }
    }
    async addTransaction(arg0: number, arg1: Time, arg2: Category, arg3: PaymentMethod, arg4: string, arg5: TransactionType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, to_candid_Category_n2(this.uploadFile, this.downloadFile, arg2), to_candid_PaymentMethod_n4(this.uploadFile, this.downloadFile, arg3), arg4, to_candid_TransactionType_n6(this.uploadFile, this.downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, to_candid_Category_n2(this.uploadFile, this.downloadFile, arg2), to_candid_PaymentMethod_n4(this.uploadFile, this.downloadFile, arg3), arg4, to_candid_TransactionType_n6(this.uploadFile, this.downloadFile, arg5));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async completeGoal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeGoal(arg0);
            return result;
        }
    }
    async deleteGoal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCategoryTotals(): Promise<Array<CategoryTotal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryTotals();
                return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryTotals();
            return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFinancialInsight(): Promise<FinancialInsight | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialInsight();
                return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialInsight();
            return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getGoals(): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoals();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoals();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getImmutableCategoryTypes(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImmutableCategoryTypes();
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImmutableCategoryTypes();
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getImmutablePaymentMethods(): Promise<Array<PaymentMethod>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImmutablePaymentMethods();
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImmutablePaymentMethods();
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPaymentMethodTotals(): Promise<Array<PaymentMethodTotal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentMethodTotals();
                return from_candid_vec_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentMethodTotals();
            return from_candid_vec_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserSettings(): Promise<UserSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveFinancialInsight(arg0: FinancialInsight): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFinancialInsight(to_candid_FinancialInsight_n42(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFinancialInsight(to_candid_FinancialInsight_n42(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async saveUserSettings(arg0: UserSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserSettings(to_candid_UserSettings_n44(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserSettings(to_candid_UserSettings_n44(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateGoal(arg0: string, arg1: string, arg2: number, arg3: number, arg4: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoal(arg0, arg1, arg2, arg3, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoal(arg0, arg1, arg2, arg3, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg4));
            return result;
        }
    }
    async updateTransaction(arg0: string, arg1: number, arg2: Time, arg3: Category, arg4: PaymentMethod, arg5: string, arg6: TransactionType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, arg1, arg2, to_candid_Category_n2(this.uploadFile, this.downloadFile, arg3), to_candid_PaymentMethod_n4(this.uploadFile, this.downloadFile, arg4), arg5, to_candid_TransactionType_n6(this.uploadFile, this.downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, arg1, arg2, to_candid_Category_n2(this.uploadFile, this.downloadFile, arg3), to_candid_PaymentMethod_n4(this.uploadFile, this.downloadFile, arg4), arg5, to_candid_TransactionType_n6(this.uploadFile, this.downloadFile, arg6));
            return result;
        }
    }
}
function from_candid_CategoryTotal_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryTotal): CategoryTotal {
    return from_candid_record_n15(uploadFile, downloadFile, value);
}
function from_candid_Category_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n17(uploadFile, downloadFile, value);
}
function from_candid_FinancialInsight_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialInsight): FinancialInsight {
    return from_candid_record_n20(uploadFile, downloadFile, value);
}
function from_candid_Goal_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
function from_candid_PaymentMethodTotal_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethodTotal): PaymentMethodTotal {
    return from_candid_record_n32(uploadFile, downloadFile, value);
}
function from_candid_PaymentMethod_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n29(uploadFile, downloadFile, value);
}
function from_candid_TransactionType_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n37(uploadFile, downloadFile, value);
}
function from_candid_Transaction_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n35(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(uploadFile, downloadFile, value);
}
function from_candid_UserSettings_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSettings): UserSettings {
    return from_candid_record_n40(uploadFile, downloadFile, value);
}
function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FinancialInsight]): FinancialInsight | null {
    return value.length === 0 ? null : from_candid_FinancialInsight_n19(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : from_candid_Category_n16(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserSettings]): UserSettings | null {
    return value.length === 0 ? null : from_candid_UserSettings_n39(uploadFile, downloadFile, value[0]);
}
function from_candid_record_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category: _Category;
    amount: number;
}): {
    category: Category;
    amount: number;
} {
    return {
        category: from_candid_Category_n16(uploadFile, downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    savingsPotential: number;
    totalIncome: number;
    incomeExpenseRatio: number;
    totalExpenses: number;
    topSpendingCategory: [] | [_Category];
    spendingTrends: Array<number>;
}): {
    savingsPotential: number;
    totalIncome: number;
    incomeExpenseRatio: number;
    totalExpenses: number;
    topSpendingCategory?: Category;
    spendingTrends: Array<number>;
} {
    return {
        savingsPotential: value.savingsPotential,
        totalIncome: value.totalIncome,
        incomeExpenseRatio: value.incomeExpenseRatio,
        totalExpenses: value.totalExpenses,
        topSpendingCategory: record_opt_to_undefined(from_candid_opt_n21(uploadFile, downloadFile, value.topSpendingCategory)),
        spendingTrends: value.spendingTrends
    };
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate: [] | [_Time];
    isCompleted: boolean;
    progressPercentage: number;
    name: string;
    targetAmount: number;
    currentAmount: number;
    startDate: _Time;
}): {
    id: string;
    endDate?: Time;
    isCompleted: boolean;
    progressPercentage: number;
    name: string;
    targetAmount: number;
    currentAmount: number;
    startDate: Time;
} {
    return {
        id: value.id,
        endDate: record_opt_to_undefined(from_candid_opt_n25(uploadFile, downloadFile, value.endDate)),
        isCompleted: value.isCompleted,
        progressPercentage: value.progressPercentage,
        name: value.name,
        targetAmount: value.targetAmount,
        currentAmount: value.currentAmount,
        startDate: value.startDate
    };
}
function from_candid_record_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: _PaymentMethod;
    amount: number;
}): {
    paymentMethod: PaymentMethod;
    amount: number;
} {
    return {
        paymentMethod: from_candid_PaymentMethod_n28(uploadFile, downloadFile, value.paymentMethod),
        amount: value.amount
    };
}
function from_candid_record_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    paymentMethod: _PaymentMethod;
    transactionType: _TransactionType;
    date: _Time;
    notes: string;
    category: _Category;
    amount: number;
}): {
    id: string;
    paymentMethod: PaymentMethod;
    transactionType: TransactionType;
    date: Time;
    notes: string;
    category: Category;
    amount: number;
} {
    return {
        id: value.id,
        paymentMethod: from_candid_PaymentMethod_n28(uploadFile, downloadFile, value.paymentMethod),
        transactionType: from_candid_TransactionType_n36(uploadFile, downloadFile, value.transactionType),
        date: value.date,
        notes: value.notes,
        category: from_candid_Category_n16(uploadFile, downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: {
        dark: null;
    } | {
        light: null;
    };
    showNotifications: boolean;
    showAnalytics: boolean;
    enableAIInsights: boolean;
    showBudgetWarnings: boolean;
    showSavingsTips: boolean;
}): {
    theme: Variant_dark_light;
    showNotifications: boolean;
    showAnalytics: boolean;
    enableAIInsights: boolean;
    showBudgetWarnings: boolean;
    showSavingsTips: boolean;
} {
    return {
        theme: from_candid_variant_n41(uploadFile, downloadFile, value.theme),
        showNotifications: value.showNotifications,
        showAnalytics: value.showAnalytics,
        enableAIInsights: value.enableAIInsights,
        showBudgetWarnings: value.showBudgetWarnings,
        showSavingsTips: value.showSavingsTips
    };
}
function from_candid_variant_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salary: null;
} | {
    other: null;
} | {
    entertainment: null;
} | {
    food: null;
} | {
    travel: null;
} | {
    rent: null;
} | {
    utilities: null;
} | {
    investment: null;
} | {
    freelance: null;
} | {
    shopping: null;
} | {
    health: null;
}): Category {
    return "salary" in value ? Category.salary : "other" in value ? Category.other : "entertainment" in value ? Category.entertainment : "food" in value ? Category.food : "travel" in value ? Category.travel : "rent" in value ? Category.rent : "utilities" in value ? Category.utilities : "investment" in value ? Category.investment : "freelance" in value ? Category.freelance : "shopping" in value ? Category.shopping : "health" in value ? Category.health : value;
}
function from_candid_variant_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    creditCard: null;
} | {
    other: null;
} | {
    cash: null;
} | {
    bankTransfer: null;
} | {
    debitCard: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "creditCard" in value ? PaymentMethod.creditCard : "other" in value ? PaymentMethod.other : "cash" in value ? PaymentMethod.cash : "bankTransfer" in value ? PaymentMethod.bankTransfer : "debitCard" in value ? PaymentMethod.debitCard : value;
}
function from_candid_variant_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    income: null;
}): TransactionType {
    return "expense" in value ? TransactionType.expense : "income" in value ? TransactionType.income : value;
}
function from_candid_variant_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dark: null;
} | {
    light: null;
}): Variant_dark_light {
    return "dark" in value ? Variant_dark_light.dark : "light" in value ? Variant_dark_light.light : value;
}
function from_candid_vec_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategoryTotal>): Array<CategoryTotal> {
    return value.map((x)=>from_candid_CategoryTotal_n14(uploadFile, downloadFile, x));
}
function from_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n23(uploadFile, downloadFile, x));
}
function from_candid_vec_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n16(uploadFile, downloadFile, x));
}
function from_candid_vec_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentMethod>): Array<PaymentMethod> {
    return value.map((x)=>from_candid_PaymentMethod_n28(uploadFile, downloadFile, x));
}
function from_candid_vec_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentMethodTotal>): Array<PaymentMethodTotal> {
    return value.map((x)=>from_candid_PaymentMethodTotal_n31(uploadFile, downloadFile, x));
}
function from_candid_vec_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n34(uploadFile, downloadFile, x));
}
function to_candid_Category_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n3(uploadFile, downloadFile, value);
}
function to_candid_FinancialInsight_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinancialInsight): _FinancialInsight {
    return to_candid_record_n43(uploadFile, downloadFile, value);
}
function to_candid_PaymentMethod_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n5(uploadFile, downloadFile, value);
}
function to_candid_TransactionType_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n7(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid_UserSettings_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserSettings): _UserSettings {
    return to_candid_record_n45(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    savingsPotential: number;
    totalIncome: number;
    incomeExpenseRatio: number;
    totalExpenses: number;
    topSpendingCategory?: Category;
    spendingTrends: Array<number>;
}): {
    savingsPotential: number;
    totalIncome: number;
    incomeExpenseRatio: number;
    totalExpenses: number;
    topSpendingCategory: [] | [_Category];
    spendingTrends: Array<number>;
} {
    return {
        savingsPotential: value.savingsPotential,
        totalIncome: value.totalIncome,
        incomeExpenseRatio: value.incomeExpenseRatio,
        totalExpenses: value.totalExpenses,
        topSpendingCategory: value.topSpendingCategory ? candid_some(to_candid_Category_n2(uploadFile, downloadFile, value.topSpendingCategory)) : candid_none(),
        spendingTrends: value.spendingTrends
    };
}
function to_candid_record_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: Variant_dark_light;
    showNotifications: boolean;
    showAnalytics: boolean;
    enableAIInsights: boolean;
    showBudgetWarnings: boolean;
    showSavingsTips: boolean;
}): {
    theme: {
        dark: null;
    } | {
        light: null;
    };
    showNotifications: boolean;
    showAnalytics: boolean;
    enableAIInsights: boolean;
    showBudgetWarnings: boolean;
    showSavingsTips: boolean;
} {
    return {
        theme: to_candid_variant_n46(uploadFile, downloadFile, value.theme),
        showNotifications: value.showNotifications,
        showAnalytics: value.showAnalytics,
        enableAIInsights: value.enableAIInsights,
        showBudgetWarnings: value.showBudgetWarnings,
        showSavingsTips: value.showSavingsTips
    };
}
function to_candid_variant_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    salary: null;
} | {
    other: null;
} | {
    entertainment: null;
} | {
    food: null;
} | {
    travel: null;
} | {
    rent: null;
} | {
    utilities: null;
} | {
    investment: null;
} | {
    freelance: null;
} | {
    shopping: null;
} | {
    health: null;
} {
    return value == Category.salary ? {
        salary: null
    } : value == Category.other ? {
        other: null
    } : value == Category.entertainment ? {
        entertainment: null
    } : value == Category.food ? {
        food: null
    } : value == Category.travel ? {
        travel: null
    } : value == Category.rent ? {
        rent: null
    } : value == Category.utilities ? {
        utilities: null
    } : value == Category.investment ? {
        investment: null
    } : value == Category.freelance ? {
        freelance: null
    } : value == Category.shopping ? {
        shopping: null
    } : value == Category.health ? {
        health: null
    } : value;
}
function to_candid_variant_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_dark_light): {
    dark: null;
} | {
    light: null;
} {
    return value == Variant_dark_light.dark ? {
        dark: null
    } : value == Variant_dark_light.light ? {
        light: null
    } : value;
}
function to_candid_variant_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    creditCard: null;
} | {
    other: null;
} | {
    cash: null;
} | {
    bankTransfer: null;
} | {
    debitCard: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.creditCard ? {
        creditCard: null
    } : value == PaymentMethod.other ? {
        other: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.bankTransfer ? {
        bankTransfer: null
    } : value == PaymentMethod.debitCard ? {
        debitCard: null
    } : value;
}
function to_candid_variant_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    expense: null;
} | {
    income: null;
} {
    return value == TransactionType.expense ? {
        expense: null
    } : value == TransactionType.income ? {
        income: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
