/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Category = IDL.Variant({
  'salary' : IDL.Null,
  'other' : IDL.Null,
  'entertainment' : IDL.Null,
  'food' : IDL.Null,
  'travel' : IDL.Null,
  'rent' : IDL.Null,
  'utilities' : IDL.Null,
  'investment' : IDL.Null,
  'freelance' : IDL.Null,
  'shopping' : IDL.Null,
  'health' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'creditCard' : IDL.Null,
  'other' : IDL.Null,
  'cash' : IDL.Null,
  'bankTransfer' : IDL.Null,
  'debitCard' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'memberSince' : Time,
});
export const CategoryTotal = IDL.Record({
  'category' : Category,
  'amount' : IDL.Float64,
});
export const FinancialInsight = IDL.Record({
  'savingsPotential' : IDL.Float64,
  'totalIncome' : IDL.Float64,
  'incomeExpenseRatio' : IDL.Float64,
  'totalExpenses' : IDL.Float64,
  'topSpendingCategory' : IDL.Opt(Category),
  'spendingTrends' : IDL.Vec(IDL.Float64),
});
export const Goal = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Opt(Time),
  'isCompleted' : IDL.Bool,
  'progressPercentage' : IDL.Float64,
  'name' : IDL.Text,
  'targetAmount' : IDL.Float64,
  'currentAmount' : IDL.Float64,
  'startDate' : Time,
});
export const PaymentMethodTotal = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'amount' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'transactionType' : TransactionType,
  'date' : Time,
  'notes' : IDL.Text,
  'category' : Category,
  'amount' : IDL.Float64,
});
export const UserSettings = IDL.Record({
  'theme' : IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null }),
  'showNotifications' : IDL.Bool,
  'showAnalytics' : IDL.Bool,
  'enableAIInsights' : IDL.Bool,
  'showBudgetWarnings' : IDL.Bool,
  'showSavingsTips' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addGoal' : IDL.Func(
      [IDL.Text, IDL.Float64, Time, IDL.Opt(Time)],
      [IDL.Text],
      [],
    ),
  'addTransaction' : IDL.Func(
      [IDL.Float64, Time, Category, PaymentMethod, IDL.Text, TransactionType],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeGoal' : IDL.Func([IDL.Text], [], []),
  'deleteGoal' : IDL.Func([IDL.Text], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryTotals' : IDL.Func([], [IDL.Vec(CategoryTotal)], ['query']),
  'getFinancialInsight' : IDL.Func([], [IDL.Opt(FinancialInsight)], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getImmutableCategoryTypes' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getImmutablePaymentMethods' : IDL.Func(
      [],
      [IDL.Vec(PaymentMethod)],
      ['query'],
    ),
  'getPaymentMethodTotals' : IDL.Func(
      [],
      [IDL.Vec(PaymentMethodTotal)],
      ['query'],
    ),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFinancialInsight' : IDL.Func([FinancialInsight], [], []),
  'saveUserSettings' : IDL.Func([UserSettings], [], []),
  'updateGoal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Opt(Time)],
      [],
      [],
    ),
  'updateTransaction' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        Time,
        Category,
        PaymentMethod,
        IDL.Text,
        TransactionType,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Category = IDL.Variant({
    'salary' : IDL.Null,
    'other' : IDL.Null,
    'entertainment' : IDL.Null,
    'food' : IDL.Null,
    'travel' : IDL.Null,
    'rent' : IDL.Null,
    'utilities' : IDL.Null,
    'investment' : IDL.Null,
    'freelance' : IDL.Null,
    'shopping' : IDL.Null,
    'health' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'creditCard' : IDL.Null,
    'other' : IDL.Null,
    'cash' : IDL.Null,
    'bankTransfer' : IDL.Null,
    'debitCard' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'memberSince' : Time,
  });
  const CategoryTotal = IDL.Record({
    'category' : Category,
    'amount' : IDL.Float64,
  });
  const FinancialInsight = IDL.Record({
    'savingsPotential' : IDL.Float64,
    'totalIncome' : IDL.Float64,
    'incomeExpenseRatio' : IDL.Float64,
    'totalExpenses' : IDL.Float64,
    'topSpendingCategory' : IDL.Opt(Category),
    'spendingTrends' : IDL.Vec(IDL.Float64),
  });
  const Goal = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Opt(Time),
    'isCompleted' : IDL.Bool,
    'progressPercentage' : IDL.Float64,
    'name' : IDL.Text,
    'targetAmount' : IDL.Float64,
    'currentAmount' : IDL.Float64,
    'startDate' : Time,
  });
  const PaymentMethodTotal = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'amount' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'transactionType' : TransactionType,
    'date' : Time,
    'notes' : IDL.Text,
    'category' : Category,
    'amount' : IDL.Float64,
  });
  const UserSettings = IDL.Record({
    'theme' : IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null }),
    'showNotifications' : IDL.Bool,
    'showAnalytics' : IDL.Bool,
    'enableAIInsights' : IDL.Bool,
    'showBudgetWarnings' : IDL.Bool,
    'showSavingsTips' : IDL.Bool,
  });
  
  return IDL.Service({
    'addGoal' : IDL.Func(
        [IDL.Text, IDL.Float64, Time, IDL.Opt(Time)],
        [IDL.Text],
        [],
      ),
    'addTransaction' : IDL.Func(
        [IDL.Float64, Time, Category, PaymentMethod, IDL.Text, TransactionType],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeGoal' : IDL.Func([IDL.Text], [], []),
    'deleteGoal' : IDL.Func([IDL.Text], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryTotals' : IDL.Func([], [IDL.Vec(CategoryTotal)], ['query']),
    'getFinancialInsight' : IDL.Func(
        [],
        [IDL.Opt(FinancialInsight)],
        ['query'],
      ),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getImmutableCategoryTypes' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getImmutablePaymentMethods' : IDL.Func(
        [],
        [IDL.Vec(PaymentMethod)],
        ['query'],
      ),
    'getPaymentMethodTotals' : IDL.Func(
        [],
        [IDL.Vec(PaymentMethodTotal)],
        ['query'],
      ),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFinancialInsight' : IDL.Func([FinancialInsight], [], []),
    'saveUserSettings' : IDL.Func([UserSettings], [], []),
    'updateGoal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Opt(Time)],
        [],
        [],
      ),
    'updateTransaction' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          Time,
          Category,
          PaymentMethod,
          IDL.Text,
          TransactionType,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };