/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'salary' : null } |
  { 'other' : null } |
  { 'entertainment' : null } |
  { 'food' : null } |
  { 'travel' : null } |
  { 'rent' : null } |
  { 'utilities' : null } |
  { 'investment' : null } |
  { 'freelance' : null } |
  { 'shopping' : null } |
  { 'health' : null };
export interface CategoryTotal { 'category' : Category, 'amount' : number }
export interface FinancialInsight {
  'savingsPotential' : number,
  'totalIncome' : number,
  'incomeExpenseRatio' : number,
  'totalExpenses' : number,
  'topSpendingCategory' : [] | [Category],
  'spendingTrends' : Array<number>,
}
export interface Goal {
  'id' : string,
  'endDate' : [] | [Time],
  'isCompleted' : boolean,
  'progressPercentage' : number,
  'name' : string,
  'targetAmount' : number,
  'currentAmount' : number,
  'startDate' : Time,
}
export type PaymentMethod = { 'upi' : null } |
  { 'creditCard' : null } |
  { 'other' : null } |
  { 'cash' : null } |
  { 'bankTransfer' : null } |
  { 'debitCard' : null };
export interface PaymentMethodTotal {
  'paymentMethod' : PaymentMethod,
  'amount' : number,
}
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'paymentMethod' : PaymentMethod,
  'transactionType' : TransactionType,
  'date' : Time,
  'notes' : string,
  'category' : Category,
  'amount' : number,
}
export type TransactionType = { 'expense' : null } |
  { 'income' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'memberSince' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'theme' : { 'dark' : null } |
    { 'light' : null },
  'showNotifications' : boolean,
  'showAnalytics' : boolean,
  'enableAIInsights' : boolean,
  'showBudgetWarnings' : boolean,
  'showSavingsTips' : boolean,
}
export interface _SERVICE {
  'addGoal' : ActorMethod<[string, number, Time, [] | [Time]], string>,
  'addTransaction' : ActorMethod<
    [number, Time, Category, PaymentMethod, string, TransactionType],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeGoal' : ActorMethod<[string], undefined>,
  'deleteGoal' : ActorMethod<[string], undefined>,
  'deleteTransaction' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryTotals' : ActorMethod<[], Array<CategoryTotal>>,
  'getFinancialInsight' : ActorMethod<[], [] | [FinancialInsight]>,
  'getGoals' : ActorMethod<[], Array<Goal>>,
  'getImmutableCategoryTypes' : ActorMethod<[], Array<Category>>,
  'getImmutablePaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'getPaymentMethodTotals' : ActorMethod<[], Array<PaymentMethodTotal>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSettings' : ActorMethod<[], [] | [UserSettings]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFinancialInsight' : ActorMethod<[FinancialInsight], undefined>,
  'saveUserSettings' : ActorMethod<[UserSettings], undefined>,
  'updateGoal' : ActorMethod<
    [string, string, number, number, [] | [Time]],
    undefined
  >,
  'updateTransaction' : ActorMethod<
    [string, number, Time, Category, PaymentMethod, string, TransactionType],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];